### ISSUE TITLE
Instance checker crash

### ISSUE THREAD

**Issue by jepke** [chuckleslove/RDMMonitor#1]
RDMMonitor.js:92
            let percent = instance.status.quests.current_count_db / instance.status.quests.total_count;
                                                 ^

TypeError: Cannot read property 'current_count_db' of undefined
    at AddInstance (/opt/rdmmonitor/RDMMonitor.js:92:50)
    at /opt/rdmmonitor/RDMMonitor.js:61:21
    at Array.forEach (<anonymous>)
    at Request.request.get [as _callback] (/opt/rdmmonitor/RDMMonitor.js:58:33)
    at Request.self.callback (/opt/rdmmonitor/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/opt/rdmmonitor/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/opt/rdmmonitor/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)

**Comment by chuckleslove** [comment]
I believe this is fixed in the current version, reopen if it's not.

**Comment by jepke** [comment]
just updated but now it doesnt run at all :) i redid my config as i saw there where some changes

Uncaught exception: TypeError: Cannot read property 'current_count_db' of undefined

**Comment by chuckleslove** [comment]
Likely have an old version of RDM that sends different format data.
